#!/bin/bash

set -e

GLOBAL_CONFIG_PATH=$HOME/.config/dce
CONFIG_FILE_NAME=.dcerc

OPTS=''
if [ -f "$PWD/$CONFIG_FILE_NAME" ]; then
    OPTS=$(grep -v '^#' "$PWD/$CONFIG_FILE_NAME")
fi
OPTS=${OPTS//$'\n'/ }

CURRENT_ENV=prod
if [ -f "$GLOBAL_CONFIG_PATH/env" ]; then
    CURRENT_ENV=$(cat "$GLOBAL_CONFIG_PATH/env")
fi

ENV=''
for env_file in .env .env.$CURRENT_ENV; do
    if [ -f "$PWD/$env_file" ]; then
        ENV="$ENV --env-file $env_file"
    fi
done

docker compose "$ENV" "$OPTS" "$@"
